{
 "title": "Homelab Metrics",
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployments",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  timestamp, count(distinct(deployment_name))\nFROM kubernetes_deployment\nwhere timestamp >= $__fromTime and timestamp <= $__toTime\nSAMPLE BY $__sampleByInterval",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  timestamp, node_count\nFROM kubernetes_node\nwhere timestamp >= $__fromTime and timestamp <= $__toTime\nSAMPLE BY $__sampleByInterval",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, count(distinct(namespace))\nFROM kubernetes_pod_container\nWHERE status = 'True'\nand timestamp >= $__fromTime and timestamp <= $__toTime\nSAMPLE BY $__sampleByInterval",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, count(distinct(pod_name))\nFROM kubernetes_pod_container\nWHERE condition = 'Ready' and timestamp >= $__fromTime and timestamp <= $__toTime\nSAMPLE BY $__sampleByInterval",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT (cast(first_not_null(kpd.cpu_usage_nanocores) as double) / 100000.0) / (cast(first_not_null(kn.capacity_cpu_cores) as double) * 100.0) as num, container_name as string\nFROM kubernetes_pod_container kpd\nJOIN kubernetes_node kn on kn.timestamp = kpd.timestamp\nLATEST ON timestamp PARTITION BY container_name",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT memory_working_set_bytes, container_name as string\nFROM kubernetes_pod_container\nLATEST ON timestamp PARTITION BY container_name",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "rawSql": "SELECT\n    timestamp,\n    abs((rx_bytes - thing1) / ((cast(timestamp as double) - thing2)  / 100.0)) * 8 AS derivative\nFROM (\n  select\n  timestamp, \n  rx_bytes,\n  LAG(rx_bytes, 1) OVER (ORDER BY timestamp) as thing1,\n  LAG(cast(timestamp as double), 1) OVER (ORDER BY timestamp) AS thing2\n  FROM kubernetes_pod_network\n  Sample by $__sampleByInterval\n)\nWHERE\n    timestamp >= $__fromTime and timestamp <= $__toTime\nORDER BY\n    timestamp;",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT\n    timestamp,\n    abs((tx_bytes - thing1) / ((cast(timestamp as double) - thing2)  / 100.0)) * 8 AS derivative\nFROM (\n  select\n  timestamp,\n  tx_bytes,\n  LAG(tx_bytes, 1) OVER (ORDER BY timestamp) as thing1,\n  LAG(cast(timestamp as double), 1) OVER (ORDER BY timestamp) AS thing2\n  FROM kubernetes_pod_network\n  Sample by $__sampleByInterval\n)\nWHERE\n    timestamp >= $__fromTime and timestamp <= $__toTime\nORDER BY\n    timestamp;\n    ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "OXN x509 Issue Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select startdate * 1000\nfrom x509_cert\nwhere common_name = 'oxn.sh'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "OXN x509 Expiry",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select (age * 1.0) / (expiry)\nfrom x509_cert\nwhere common_name = 'oxn.sh'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "OXN x509 End Date",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select enddate * 1000\nfrom x509_cert\nwhere common_name = 'oxn.sh'",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "Exodus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 22 },
   "options": {
    "content": "<h1 style=\"text-align:center\">Exodus</h1>"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT uptime \nFROM system\nwhere host = 'exodus' ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT available_percent\nFROM mem\nwhere host = 'exodus'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Root Usage",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT fs_used_bytes \nFROM kubernetes_node\nWHERE host = 'exodus'",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT fs_available_bytes \nFROM kubernetes_node\nwhere host = 'exodus' ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (cast(last_not_null(cpu_usage_nanocores) as double) / 100000.0) / (cast(last_not_null(capacity_cpu_cores) as double) * 100.0)\nFROM kubernetes_node\nwhere host = 'exodus'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT jitter \nFROM internet_speed\nwhere host = 'exodus' ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT download \nFROM internet_speed\nwhere host = 'exodus' ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT upload \nFROM internet_speed\nWHERE host = 'exodus' ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT latency \nFROM internet_speed\nWHERE host = 'exodus' ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, download \nFROM internet_speed\nWHERE host = 'exodus' ",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT timestamp, upload \nFROM internet_speed\nWHERE host = 'exodus' ",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "CPU Temps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, feature, temp_input \nFROM sensors\nWHERE host = 'exodus' and chip = 'coretemp-isa-0000' and feature != 'package_id_0'  and timestamp >= $__fromTime and timestamp <= $__toTime\nSAMPLE BY $__sampleByInterval",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Temps",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT temp_input \nFROM sensors\nWHERE host = 'exodus' and chip ilike 'nvme%' and feature = 'sensor_2'",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT temp_input \nFROM sensors\nWHERE host = 'exodus' and chip = 'iwlwifi_1-virtual-0' and feature = 'temp1'",
     "selectedFormat": 2
    },
    {
     "rawSql": "SELECT temp_input \nFROM sensors\nWHERE host = 'exodus' and chip = 'coretemp-isa-0000' and feature = 'package_id_0'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, (cast(first_not_null(cpu_usage_nanocores) as double) / 100000.0) / (cast(first_not_null(capacity_cpu_cores) as double) * 100.0) as num\nFROM kubernetes_node\nWHERE host = 'exodus' and timestamp >= $__fromTime and timestamp <= $__toTime\nSAMPLE BY $__sampleByInterval",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, memory_working_set_bytes \nFROM kubernetes_node\nWHERE host = 'exodus' and timestamp >= $__fromTime and timestamp <= $__toTime\nSAMPLE BY $__sampleByInterval",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"W\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"W\" and\n    r._field == \"value\"\n  )\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}