{
 "title": "Room",
 "panels": [
  {
   "title": "Weather",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp, state\nfrom qss\nwhere entity_id = 'weather.forecast_home'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "NOX",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_sen55_nox'\nsample by 1m",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, entity_id, json_extract(attributes, '$.uv_index')::float\nfrom qss\nwhere entity_id = 'weather.forecast_home'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Weather",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, state\nfrom qss\nwhere entity_id = 'weather.forecast_home'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "CO2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as int)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_co2'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as int)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_co2'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "VOC",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as int)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_sen55_voc'",
     "selectedFormat": 2
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 } },
  {
   "title": "VOC Quality",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select timestamp, state\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_voc_quality'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Particulates",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, entity_id, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_pm_10_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_1_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_2_5_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_4_m_weight_concentration'\nsample by 1m;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Particulates",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 12 },
   "targets": [
    {
     "rawSql": "select timestamp, entity_id, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_pm_10_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_1_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_2_5_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_4_m_weight_concentration'\nsample by 1m;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "PM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, entity_id, cast(state as double) as val\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_pm_1_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_2_5_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_4_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_10_m_weight_concentration'\nlatest on timestamp partition by entity_id",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_sen55_humidity'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "select timestamp, entity_id, json_extract(attributes, '$.humidity')::float\nfrom qss\nwhere entity_id = 'weather.forecast_home'",
     "selectedFormat": 2
    },
    {
     "rawSql": "select timestamp, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_sen55_humidity'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Particulates",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 6, "x": 2, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "select timestamp, entity_id, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_pm_10_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_1_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_2_5_m_weight_concentration'\n  or entity_id = 'sensor.apollo_air_1_0ec7e0_pm_4_m_weight_concentration'\nsample by 1m;",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "rawSql": "select timestamp, entity_id, json_extract(attributes, '$.pressure')::float\nfrom qss\nwhere entity_id = 'weather.forecast_home'",
     "selectedFormat": 2
    },
    {
     "rawSql": "select timestamp, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_dps310_pressure'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_dps310_pressure'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_sen55_temperature'",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "select timestamp, cast(state as double)\nfrom qss\nwhere entity_id = 'sensor.apollo_air_1_0ec7e0_sen55_temperature'",
     "selectedFormat": 2
    },
    {
     "rawSql": "select timestamp, entity_id, json_extract(attributes, '$.current_temperature')::float\nfrom qss\nwhere entity_id = 'climate.ethan'",
     "selectedFormat": 2
    },
    {
     "rawSql": "select timestamp, entity_id, json_extract(attributes, '$.temperature')::float\nfrom qss\nwhere entity_id = 'weather.forecast_home'",
     "selectedFormat": 2
    }
   ]
  }
 ]
}